# Generated by Django 5.2.3 on 2025-07-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
