# Generated by Django 5.2.3 on 2025-07-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='national_id',
            field=models.CharField(default='dsdksdklj2309232', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
