# Generated by Django 5.2.3 on 2025-07-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
