# Generated by Django 5.2.3 on 2025-07-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
