# Generated by Django 5.2.3 on 2025-07-24 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patientprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='national_id',
        ),
    ]
