# Generated by Django 5.2.3 on 2025-07-27 00:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_patientprofile_national_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='current_condition',
            new_name='current_diagnosis',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='medications',
            new_name='current_medications',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='history',
            new_name='family_history',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies',
            field=models.TextField(default=datetime.datetime(2025, 7, 27, 0, 46, 48, 763339, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='surgery',
            field=models.TextField(default=datetime.datetime(2025, 7, 27, 0, 47, 27, 540150, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='surgical_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(default=datetime.datetime(2025, 7, 27, 0, 47, 34, 775337, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_note',
            field=models.TextField(default=datetime.datetime(2025, 7, 27, 0, 47, 40, 57264, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_signs',
            field=models.TextField(default=datetime.datetime(2025, 7, 27, 0, 47, 43, 138646, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_illness', models.TextField()),
                ('past_medications', models.TextField()),
                ('old_doctor_notes', models.TextField()),
                ('surgeries', models.TextField()),
                ('allergies', models.TextField()),
                ('family_history', models.TextField()),
                ('medication', models.TextField()),
                ('treatment_note', models.TextField()),
                ('symptoms', models.TextField()),
                ('vital_signs', models.TextField()),
                ('visited_date', models.DateField()),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
            ],
        ),
    ]
