# Generated by Django 5.2.3 on 2025-07-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notes_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='gender', max_length=10),
            preserve_default=False,
        ),
    ]
